# Generated by Django 5.1.7 on 2025-03-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_position_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
