# Generated by Django 5.1.7 on 2025-03-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_comment_task_alter_stage_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(upload_to='files/%d/'),
        ),
    ]
