# Generated by Django 5.1.7 on 2025-03-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('legal', 'Legal'), ('individual', 'Individual')], default='legal', max_length=150),
        ),
    ]
