services:
  backend:
    build:
      context: ../
      dockerfile: ./.deploy/Dockerfile
    container_name: buro_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: always
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ../.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    container_name: buro_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: '${DB_NAME:-buro}'
      POSTGRES_USER: '${DB_USER:-postgres}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-QWEasd123}'
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: buro_nginx
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
  frontend:
  static_volume:
  media_volume:

networks:
  app-network: